dist: xenial
language: bash

services:
  - docker

matrix:
  include:
    - env: flavour=latest BUILD_TAG=jakzal/phpqa:travis-php7.3-latest PHP_VERSION=7.3 BUILD_NIGHTLY=true UPDATE_TOOLBOX=true
  fast_finish: true

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - git config user.email 'jakub@zalas.pl' && git config user.name 'Jakub Zalas'

script:
  - make build-$flavour
  - docker run -it --rm $BUILD_TAG php -v | grep 'PHP '$PHP_VERSION
  - docker run -it --rm $BUILD_TAG php /tools/toolbox test
  - docker run -it --rm $BUILD_TAG

after_script:
  - docker images

after_success:
  - |
    test "$TRAVIS_EVENT_TYPE" == "cron" && test "$TRIGGER_DOCKER_HUB" == "true" && \
      curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}' -X POST https://registry.hub.docker.com/u/jakzal/phpqa/trigger/$DOCKER_HUB_TRIGGER_TOKEN/
  - test "$TRAVIS_EVENT_TYPE" == "cron" && test "$BUILD_NIGHTLY" == "true" && make build-nightly-$flavour
  - test "$UPDATE_TOOLBOX" == "true" && make update-toolbox-pr

env:
  global:
    - secure: "iO9RzZwdZiq/txA3qaKrcEgGePvBaIEQd9Znh4JMNlynunJ21ewgqzFKYlDejEqdc3Q9KCwDSlfXSaJ1mNPWxyEjBcdVWNe/IRj5+5U/bbczio4mKZ7dfw/ocCjlpeSkmCyPF3CwKmcybzWk9wQiWZkXrGdwdfzdwWgfmDb/gKzrDO3LQtEalnSiqAu8E7aE5Mwrul+0zn1IqHU3zu46GPYfs7hOpgNXg7v3L/GT8L/WGbTzRwDN0miNewxiY61J4U9ktyTeOk4mX01+lACTZuJCQe9ZKX2MatY8Bs+O9RxQSK2EAAZ4Pi25Yim9g/ry+FaV4a6K+4u/zvQKwZLjW96Hm8+/1gGfYecPOXzw7FUEEow+xzY5jyAuQpGATrXRiay7sT1bQlS6Ga7t2KATS0ifgatzDGK3LRFzlcXJkO2lD5z3uH7M5ft9eVUkVtr51BtP5Q7vwv26uq/+0/NS+9vVZe9XzK1Ew4SpdU3Z0Y7mJH4PrOTkjIOC+8j1Xu+FcqVynEzsUn1l3Bka+Y0bICekU6QrzFn1PfhRBypZHy/k0gndhXBvGXAU9qA4QscMDwdSMAjMDC/i1D/qOk5KeGHoG6/CtocMLXXB+k8MCLA0LX6uHRMEqUgIUyEKX+14luFBeMbfUCOF1cXozqOOVZnm4pgSJMddl3+AvRaQIq0="
    - secure: "ddd+1gMQ/ll8o3MZ8g8HQl7RsawJHETzUq7rncNQbJRc29vZmDfOcDworCsjJUmOQ9rIADxcylFlU1HXuEjkh9nmE78o8YMI44fJPHIGbYvuw6wvlPYR/GEqdmAhy8EE94eZQMLROhBFqj8J70H2Prpy/06+YvijtPipbEjNd3w2RVLjiyYj1BBC5i5psIXbX/OHfFsKDOHQv5ZIWeRvdeTW951bOPdEbCbOWKwz4cz4xvggJAMVlclbqdHqNFz2YWDAhyglGgwXt6dapRQuYskT4kXfht+CDIhulIdiEgRDaKM6PzKS7Irxv7P18VCtFbsbwf7LGDMbnvio5mOPRp2nk6VK5wdiBUyKQGAR6cuc2X3dpDJsu/zImJspqhLeYYeYcUSDQu6Z2QYZMk5my7A3VHsc9h5DFKwkGBDsD7Y8AfxDAbNah3+B9hNM0t+MaoQDou0vrcGrjtG6pMKEE6X3Ilpe6IebtAbby3RGIZjpU04OqnY8Tv1hCmQ+gEN/6eLJxqjEwHp6KZ7VGhH8ceMlpXJ+qhW1zGqcU5TNrO4ljb8ibIO+PsYDTuXR8YhVzm050yeKb4vtPkeFNBmDesKKGlK9JFb3aeRxGy9O7dx5Hxgq51rZlwuFtccOb8shYwMmk7lWCPTY5WehN6iYVVTA6Ky989aWPlmuK/pOUdw="
    - secure: "m9Q8Ekvm6LWkRRUmuSBZiVfgcwt/YFQCwRgzDEvMRR1LHFirgdAPZw18m5pFXr9YzkA3TGP3mUzqE3UAAjof7hDbBkUbiZL/6ynLRIWKj3EyWmViYdmVAQSNh26UBagL9m8ZLmRBvAfpD9My8XY/XSFYMnMQSeLqdpYbWE0GF9+aCJ1hlGpavycSrw4rjarLuvzHgWFNSFX13FQBYFMmBGJjkWi8xiT1yKCS6sMjH3JfenVfcDUlzTorR68463eHeZ1sUtZFGPXak9LczEcZpc8FhZIoWdJ+33QTzhh3qOXHWmcpxVMyF24I8JYn8N3PSlEx39jCaKkdPcoYL1jMaGyDwnftAFrtyYNANU7R+Bp5r8HQ2F1qEkLNIlEKZtxSQA4dTXtwkB5cNktaX5srhL7wdkhj01tGhyA+P5cy5UXGk2zUYFW8Yrk3kxjh0+FJC9pHtVlObFMJJqD8SVQCO1Z+CyZ+wv2MH5BhhQstQnZY3pBSwoSHgqTNvjioUjOwBUGy50mOvUGjtEzo/k1Svzxcw521SNACqfBwYhVlc8VP/3gPxZ+UwZNsnQpTfVDHxhaAhfTTG69g+LP4oSP0OxUlpGffzQdl1/GLqXAANRpgfDKQxzY/PMhkkwhQwhzfXbbpTeq70MbvhgQmUjUyFDKo8uETgNmP5MiyIVxoQSI="

addons:
  snaps:
  - name: hub
    classic: true
